name: Pull Request CI/CD
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:

jobs:
  primary:
    # see https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v4
      - name: Print versions
        run: |
          cat /etc/os-release
          node -v
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Run lint
        run: npm run lint
